version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  go: circleci/go@1.7.0

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/go:1.21.6-node

jobs:
  security_scans:
    <<: *defaults
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
  test:
    <<: *defaults
    steps:
      - checkout
      - go/install:
          version: "1.21"
      - go/load-cache:
          key: test_leaky_vessels_ebpf_detector
      - run:
          name: Run tests
          command: "sudo go test ebpf-detector/..."
          no_output_timeout: 3m
      - go/save-cache:
          key: test_leaky_vessels_ebpf_detector
          path: /home/circleci/.go_workspace/pkg/mod

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan: # DO NOT REMOVE OR MOVE THIS LINE
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-security-labs
      - security_scans:
          name: Security Scans
          context:
            - security-labs-snyk
      - test:
          name: Test
          filters:
            branches:
              ignore:
                - main
