version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  go: snyk/go@1.1.0
  gotest: gotest/tools@0.0.14

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/go:1.21.6-node

jobs:
  security_scans:
    <<: *defaults
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
  test:
    <<: *defaults
    steps:
      - checkout
      - go/install:
          version: "1.21.5"
      - run:
          name: Run tests
          command: "sudo /usr/local/go/bin/go test ebpf-detector/..."
          no_output_timeout: 3m

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan: # DO NOT REMOVE OR MOVE THIS LINE
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-security-labs
      - security_scans:
          name: Security Scans
          context:
            - security-labs-snyk
      - test:
          name: Test
          filters:
            branches:
              ignore:
                - main
